development:
  adapter: postgresql
  encoding: unicode
  database: cogsmart_dev
  host: localhost
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: cogsmart_test
  host: localhost
  pool: 5
  username: 
  password: 
